use QLDA
select  
substring(DCHI,charindex('',DCHI)+1,charindex(',',DCHI)
- charindex('',DCHI)-1) as 'địa chỉ'
from NHANVIEN

--IF --ELSE 
IF[BIỂU THỨC ĐIỀU KIỆN]
BEGIN
-- NẾU KHỐI CÂU LỆNH IF PHỨC TẠP THỲ BỎ VÀO 
--BEGIN -END , CÒN NẾU ĐƠN GIẢN THÌ THÔI
END
ELSE
BEGIN
END

DECLARE @DIEM_TB FLOAT
SET @DIEM_TB =6
IF @DIEM_TB < 5 
	PRINT 'YEU'
ELSE 
	PRINT 'TRUNG BINH'

--VIẾT CHƯƠNG TRÌNH KIỂM TRA SỐ NGUYÊN TỐ CÓ PHẢI LÀ SỐ NGUYÊN TỐ HAY KHÔNG

DECLARE @SNT INT  =15 
DECLARE @I INT = 2
DECLARE @ISPRIME BIT = 1 

WHILE @I<SQRT(@SNT)
BEGIN
IF @SNT % @I = 0
	BEGIN
		SET @ISPRIME = 0 
		BREAK
	END
	SET @I=@I+1
END
	IF @ISPRIME = 1
		BEGIN 
			SELECT @SNT 'IS PRIME'
		END
	ELSE 
		BEGIN
			SELECT @SNT 'IS NOT PRIME'
		PRINT ' LA SO NGUYEN TO'
	END

USE QLDA
IF((SELECT COUNT (*) FROM NHANVIEN WHERE LUONG >30000) >0)
	BEGIN
		PRINT 'DANH SÁCH NHÂN VIÊN LƯƠNG LƯƠN HƠN 30000'
		SELECT * FROM NHANVIEN WHERE LUONG >300000
	END
ELSE
	PRINT 'KHONG CO AI LUONG <30000'


	-- IF - EXITS
	-- IF - EXITS (CÂU LỆNH SELECT )
		-- CÂU LỆNH 1 | KHỐI CÂU LỆNH
	-- ELSE 
		-- CÂU LỆNH 1 | KHỐI CÂU LỆNH

IF EXISTS (SELECT * FROM NHANVIEN WHERE LUONG >30000)
BEGIN 
	PRINT 'DANH SÁCH NHÂN VIÊN LUONG > 30000'
	SELECT * FROM NHANVIEN WHERE LUONG >30000
END
ELSE 
	PRINT 'KHONG CO AI DI LUONG <30000'

-- CHECK DATABASE TỒN TẠI
	IF EXISTS (
		SELECT NAME 
			FROM SYS.DATABASES 
			WHERE NAME = N'DATABASESNAME') -- CHECK  NẾU TÊN DATABASE ĐÃ TỒN TẠI

DROP DATABASE databaseName -- XÓA LUÔN DATABASE
GO

CREATE DATABASE databaseName  --- TẠO MỚI
GO

-- IIF FUNCION : HÀM IFF
-- CÚ PHÁP : IFF (EXPRESSION , EXPR_TRUE , EXPR _FALSE )
-- NẾU LƯƠNG LỚN HƠN 30000 LÀ TRƯỞNG PHÒNG CÒN LẠI LÀ NHÂN VIÊN

SELECT IIF (LUONG >30000 , 'TRUONG PHONG','NHANVIEN')  AS CHUCVU , TENNV , LUONG FROM NHANVIEN


--CASE 
--THÊM TIỀN TỐ MR HOẶC MS TÙY VÀO PHÁI NAM HAY NỮ
SELECT * FROM NHANVIEN
SELECT TENNV = CASE PHAI 
WHEN 'NAM' THEN 'MR.'+ TENNV
WHEN N'NỮ' THEN 'MS.' + TENNV
ELSE 'UNISEX.'   + TENNV
END
FROM NHANVIEN

--TẠO THÊM CỘT THUẾ DỰA VÀO MỨC LƯƠNG
--NẾU LƯƠNG 0-25000 ĐÓNG 10%
--NẾU LƯƠNG 25000-30000 ĐÓNG 12%
--NẾU LƯƠNG 30000-40000 DÓNG 15%
--NẾU LƯƠNG 40000-50000 ĐÓNG 25%

SELECT TENNV , LUONG , THUE = CASE
WHEN LUONG BETWEEN 0 AND 25000 THEN LUONG *0.1
WHEN LUONG BETWEEN 25000 AND 30000 THEN LUONG *0.12
WHEN LUONG BETWEEN 30000 AND 40000 THEN LUONG *0.15
WHEN LUONG BETWEEN 40000 AND 50000 THEN LUONG *0.2 
WHEN LUONG >50000 THEN LUONG *0.25
END
FROM NHANVIEN

--WHILE 
DECLARE @DEM int = 1
WHILE @DEM <6
BEGIN
	PRINT 'HOC MOI QUA DC MON'
	SET @DEM = @DEM+1
END
PRINT N'KHONG HOC THY NHOT'


USE QLDA 
DECLARE @LUONG_TB FLOAT 
SELECT @LUONG_TB  = AVG(LUONG)
FROM NHANVIEN JOIN PHONGBAN ON NHANVIEN.PHG= PHONGBAN.MAPHG 

	SELECT TENNV , GIATRI = CASE 
	WHEN LUONG < AVG(@LUONG_TB) THEN 'DC TANG LUONG' 
	WHEN LUONG > AVG(@LUONG_TB) THEN 'KHONG TANG LUONG'
	END
	FROM NHANVIEN