use qlda

--store procedure - CÓ THAM SỐ HOWAJSC  KHÔNG CÓ THAM SỐ
-- CÔNG THỨC
--CREATE PROCEDURE / PROC + SP_NAME
	--@PARAMETER_DATATYPE
--AS
--BEGIN
	-- KHỐI CÂU LỆNH QUERY
--END



--VIẾT CÂU LỆNH THỦ TỤC LẤY RA THÔNG TIN TÊN NHÂN VIÊN, ĐỊA CHỈ, PHÒNG BAN, TÊN PHÒNG BAN
CREATE PROCEDURE SP_ThongTinNhanVien1
AS
BEGIN
SELECT TENNV, HONV , DCHI ,MAPHG ,TENPHG  FROM NHANVIEN
INNER JOIN PHONGBAN ON PHONGBAN.MAPHG = NHANVIEN.PHG 
END;

EXEC SP_ThongTinNhanVien1

ALTER PROC SP_THONGTINNHANVIEN1
AS
BEGIN
END

-- TẠO THỦ TỤC LẤY RA THÔNG TIN THEO MÃ
--THAM SỐ TRUYỀN VÀO LÀ MA 001

ALTER PROC SP_MA
@MA_NV NVARCHAR(50)
AS
BEGIN
	SELECT * FROM NHANVIEN WHERE MANV LIKE @MA_NV
END

EXEC SP_MA '001'

--TẠO THỦ TỤC LẤY RA THÔNG TIN MÃ NHÂN VIÊN , TÊN NHÂN VIÊN , TÊN PHÒNG BAN
-- THEO MÃ PHÒNG BAN VÀ MÃ NHÂN VIÊN CẦN LẤY
USE QLDA
SELECT TENNV, TENPHG, MANV FROM NHANVIEN 
JOIN PHONGBAN ON PHONGBAN.MAPHG = NHANVIEN.PHG

ALTER PROC SP_LAYTT
@MAPB INT ,
@MANV NVARCHAR(50)
AS
BEGIN
	SELECT TENNV, TENPHG, MANV , MAPHG FROM NHANVIEN 
JOIN PHONGBAN ON PHONGBAN.MAPHG = NHANVIEN.PHG
WHERE MAPHG = @MAPB AND MANV = @MANV
END

EXEC SP_LAYTT  4,'001'

	


