CREATE DATABASE DEMO_COM24

CREATE TABLE KESACH (
MAKS VARCHAR(20)  PRIMARY KEY ,
TENKESACH NVARCHAR(20) NOT NULL ,
MOTA NVARCHAR(50) NOT NULL
);

CREATE TABLE SACH (
MASACH VARCHAR(20) PRIMARY KEY ,
TEN NVARCHAR(20) NOT NULL ,
TACGIA NVARCHAR (20) NOT NULL ,
THELOAI NVARCHAR(20) NOT NULL ,
GIABAN MONEY
);

CREATE TABLE CHITIETKESACH (
MASACH VARCHAR(20) FOREIGN KEY REFERENCES SACH(MASACH) ,
MAKS VARCHAR(20) FOREIGN KEY REFERENCES KESACH(MAKS),
SOLUONG INT
);

CREATE PROC sp_KESACH 
@MAKS VARCHAR(20) ,
@TENKESACH VARCHAR (20),
@MOTA NVARCHAR(50) 
AS
	BEGIN
		IF @MAKS IS NULL OR
		   @TENKESACH IS NULL
		   PRINT 'KHONG HOP LE'
		ELSE 
			INSERT INTO KESACH VALUES (@MAKS ,@TENKESACH ,@MOTA)

	END

	EXEC sp_KESACH '01' ,'DAY A','HANG NGOAI CUNG'
	EXEC sp_KESACH '02' ,'DAY B','HANG NGOAI CANH DAY A'
	EXEC sp_KESACH '03' ,'DAY C','HANG NGOAI CANH DAY B'


CREATE PROC sp_SACH
@MASACH VARCHAR(20),
@TEN NVARCHAR(20) ,
@TACGIA NVARCHAR (20), 
@THELOAI NVARCHAR(20) ,
@GIABAN MONEY
AS
	BEGIN
		IF @MASACH IS NULL OR
		   @TEN IS NULL OR
		   @TACGIA IS NULL OR
		   @THELOAI IS NULL
			PRINT 'KHONG HOP LE'
		ELSE
			INSERT INTO SACH VALUES (@MASACH ,@TEN ,@TACGIA ,@THELOAI ,@GIABAN)
	END

		EXEC sp_SACH 'HT01' , 'MIKAMI', 'JAV' , 'HENTAI' ,500000
		EXEC sp_SACH 'HT02' , 'HATANO', 'JAV' , 'HENTAI' ,600000
		EXEC sp_SACH 'HT03' , 'OZAWA', 'JAV' , 'HENTAI' ,700000

CREATE PROC sp_CHITIETKESACH 
@MASACH VARCHAR(20) ,
@MAKS VARCHAR(20) ,
@SOLUONG INT
AS
	BEGIN
		IF @MASACH IS NULL OR
		   @MAKS IS NULL
		   PRINT 'KHONG HOP LE'
	ELSE
		INSERT INTO CHITIETKESACH VALUES (@MASACH ,@MAKS ,@SOLUONG)
	END

	EXEC sp_CHITIETKESACH 'HT01' , '01' , 5
	EXEC sp_CHITIETKESACH 'HT02' , '02' , 4
	EXEC sp_CHITIETKESACH 'HT03' , '03' , 3


ALTER PROC sp_DOANHTHU
AS
	BEGIN
SELECT  SACH.MASACH,TEN , SUM(GIABAN*SOLUONG) AS 'TONG DOANH THU'
FROM SACH 
INNER JOIN CHITIETKESACH ON CHITIETKESACH.MASACH = SACH.MASACH 
GROUP BY SACH.MASACH,TEN
	END

	EXEC sp_DOANHTHU

CREATE PROC sp_XoaSach1
AS
BEGIN
    SET NOCOUNT ON;
    
    -- Xóa sách không có trong kệ sách
    DELETE FROM SACH
    WHERE MASACH NOT IN (SELECT MASACH FROM KESACH);
    
    -- In ra số lượng sách đã bị xóa
    SELECT @@ROWCOUNT AS 'BooksDeleted';
END

EXEC sp_XoaSach1

ALTER PROC sp_timsachANDupdate
@THELOAI NVARCHAR(20),
@UPDATETHELOAI NVARCHAR (20)
AS	
	BEGIN
		IF @THELOAI IS NULL OR
			@UPDATETHELOAI IS NULL
		PRINT 'NHAP DEO DAU MA TIM ?'
		ELSE 
		UPDATE SACH
		SET THELOAI = @UPDATETHELOAI
		WHERE @THELOAI =THELOAI
	END

	EXEC sp_timsachANDupdate 'HENTAI' ,'PHIMNGUOILON'

	SELECT * FROM SACH

ALTER PROC	sp_xoaAll
AS
	BEGIN
	DELETE  FROM CHITIETKESACH
	FROM SACH
	INNER JOIN CHITIETKESACH ON CHITIETKESACH.MASACH = SACH.MASACH
	WHERE SOLUONG <10 OR GIABAN <50000
	END

	EXEC sp_xoaAll

	SELECT * FROM CHITIETKESACH
	SELECT * FROM SACH
	SELECT * FROM KESACH 

