use QLDA

--trigger 
-- công thức

create trigger TG_name on tablename 
for (delete, insert , update )
as
	begin
	--khối câu lệnh thực thi
	ROLLBACK
	end

-- vd1
USE QLDA
ALTER TRIGGER tg_checkluong ON NHANVIEN FOR INSERT 
AS
	IF ( SELECT LUONG FROM INSERTED ) <50000
	BEGIN
		PRINT 'TIEN LUONG PHAI TOI THIEU 50000'
		ROLLBACK
		END
INSERT INTO NHANVIEN
VALUES ('NGUYEN' , 'VAN' , 'A' , '114' , '2005-02-01' , 'HN' , 'NAM',55500 ,'005' ,4)
SELECT * FROM NHANVIEN

-- CẬP NHẬT LƯƠNG CHO NHÂN VIÊN 
ALTER TRIGGER tg_capnhatluong ON NHANVIEN FOR UPDATE
AS
	IF(SELECT LUONG FROM INSERTED )<5000
	BEGIN
		PRINT 'lUONG TOI DA LA 5000'
		ROLLBACK
	END

UPDATE NHANVIEN
SET LUONG =20000
WHERE MANV LIKE '005'
SELECT * FROM NHANVIEN 

--TRIGGER DELETE
--TẠO TRIGGER DELETE KHÔNG CHO PHÉP XÓA NHÂN VIÊN CÓ MÃ 001
ALTER TRIGGER TG_DELLCHOXOA001 ON NHANVIEN FOR DELETE
AS
	IF '001' IN (SELECT MANV FROM deleted ) 
	BEGIN
	PRINT N'MÃ NÀY KHÔNG CÓ THỂ XÓA '
	ROLLBACK
	END

	DELETE NHANVIEN
	WHERE MANV LIKE '005'

	SELECT * FROM NHANVIEN


--VIẾT TRIGGER ĐẾM SỐ LƯỢNG NHÂN VIÊN BỊ XÓA KHI CÓ CÂU LỆNH XÓA TRÊN BẢNG NHÂN VIÊN
CREATE TRIGGER TG_DEM ON NHANVIEN FOR DELETE 
AS
	BEGIN
	DECLARE @DEM  VARCHAR(10) 
	SELECT @DEM = COUNT (*) FROM deleted
	PRINT 'SO LUONG NHAN VIEN DA XOA = ' +@DEM
	END

	DELETE FROM NHANVIEN WHERE MANV = 'NV01'
	

--VIẾT TRIGGER XÓA NHÂN VIN CÓ MÃ  003 ĐỒNG THỜI DỮ LIỆU Ở BẢNG PHÂN CÔNG CỦA NHÂN VIÊN ĐÓ CŨNG BỊ XÓA

ALTER TRIGGER TG_XOA003 ON PHANCONG FOR DELETE
AS
	IF '003' IN (SELECT MA_NVIEN FROM deleted)
	BEGIN
	PRINT 'DONE!'
	END

	DELETE PHANCONG 
	WHERE MA_NVIEN LIKE '003'
	
	DELETE FROM NHANVIEN 
	WHERE MANV LIKE '003' 

	SELECT * FROM PHANCONG
	SELECT * FROM NHANVIEN

	




